schema:
  repository: ../yang-repo

  searchPaths:
    - ietf
    - openconfig
    - nokia/srlinux

  modules:
    - openconfig-system
    - openconfig-interfaces
    - openconfig-network-instance

  cache:
    enabled: true

  loader:
    recursive: true

  parser:
    implementation: ygot
